title: Android Games Showcase

description: >- # this means to ignore newlines until "baseurl:"
  A curated list of good and interesting Android games, focusing on premium titles.
baseurl: "/android-games-website" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username: abduznik

# Build settings
collections:
  games:
    output: true
    permalink: /games/:title/
theme: minima
minima:
  skin: dark
plugins:
  - jekyll-feed
  - fix_image_paths

safe: true

# The `whitelist` option is deprecated and has been replaced by `plugins`.
# You can remove the `whitelist` section entirely as its functionality is
# now handled by the `plugins` array.
# For example, if you were trying to whitelist a plugin, you would simply add it to the `plugins` array.
# whitelist:
#  - jekyll-feed
#  - fix_image_paths

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/